# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=15, unique=True)),
                ('distribucion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=140)),
                ('ip', models.GenericIPAddressField()),
                ('puerto', models.PositiveIntegerField(default=22)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
